# Generated by Django 5.2.5 on 2025-11-20 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_image_category_slug_subcategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='slug',
        ),
    ]
