# Generated by Django 5.2.8 on 2025-11-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='New Notification', max_length=255),
        ),
    ]
