# Generated by Django 5.2.8 on 2025-11-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_uernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='uernotification',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uernotification',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
