# Generated by Django 5.2.8 on 2025-11-25 05:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_uernotification_link_alter_uernotification_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UerNotification',
            new_name='UserNotification',
        ),
    ]
