# Generated by Django 5.2.8 on 2025-11-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_uernotification_usernotification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernotification',
            old_name='link',
            new_name='product_name',
        ),
        migrations.AddField(
            model_name='usernotification',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='title',
            field=models.CharField(default='New Notification', max_length=255),
        ),
    ]
